# Generated by Django 5.0.7 on 2024-07-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('price', models.FloatField()),
            ],
        ),
    ]
